### ISSUE TITLE
The algorithms video link is dead.

### ISSUE THREAD

**Issue by awalvie** [llSourcell/Learn_Computer_Science_in_5_Months#7]
As the issue says the link to the MIT Website does not work anymore.

**Comment by onlurking** [comment]
You mean the https://courses.csail.mit.edu/6.006/fall11/notes.shtml in **Week 5-6 (Algorithms)**
@Awalvie? Can you check again? The link is fine for me.

**Comment by awalvie** [comment]
Yeah still isn't working. Maybe it's my ISP. Well if it's working then I guess we can consider the issue coded.
